apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-claim
spec:
  storageClassName: "{{ .Values.storageClassName }}"
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: "{{ .Values.storageSize }}"