---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add "{{ inventory_hostname }}" to /etc/hosts
  template:
    src: "hosts.j2"
    dest: "/etc/hosts" 

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Install packages
  apt:
    name: "{{ base_packages }}"

