---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add "{{ inventory_hostname }}" to /etc/hosts
  template:
    src: "hosts.j2"
    dest: "/etc/hosts" 

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Install packages
  apt:
    name: "{{ base_packages }}"

- name: Start rpc-statd service
  service:
    name: "rpc-statd"
    state: started

- name: Enable rpc-statd service at boot
  service:
    name: "rpc-statd"
    enabled: yes
