---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add '{{ inventory_hostname }}' to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^(127\.0\.0\.1\s+)(.*\blocalhost)$'
    line: '127.0.0.1\t\2 {{ inventory_hostname }}'
    backrefs: yes

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Install packages
  apt:
    name: "{{ base_packages }}"

