---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add IP to '/etc/fstab'
  replace:
    path: /etc/fstab
    regexp: '^(192\.168\.1\.210:/mnt/ssd/tftpboot)( .*)?$'
    replace: '\1/{{ ansible_host }}\2'

