---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Replace 'node' inside of /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^(127\.0\.1\.1\s+).*node$'
    line: '\1{{ ansible_hostname }}'
    backrefs: yes

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Install packages
  apt:
    name: "{{ base_packages }}"

