---
- name: Include snap role
  include_role:
    name: snap

- name: Check if MicroK8s is installed
  command: "snap list | grep microk8s"
  register: microk8s_snap_list
  check_mode: no
  ignore_errors: yes

- name: Print debug message if MicroK8s is not installed
  debug:
    msg: "No MicroK8s pacakge found."
  when: microk8s_snap_list.failed

- name: Install MicroK8s
  when: microk8s_snap_list.failed
  block:
    - name: Load the snapd daemon
      systemd:
        name: snapd
        state: started
        enabled: yes
    
    - name: Install MicroK8s snap
      snap:
        name: microk8s
        classic: yes
        state: present
    
    - name: Stop MicroK8s
      command: "/snap/bin/microk8s stop"

    - name: Remove the containerd directory
      file:
        path: /var/snap/microk8s/common/var/lib/containerd
        state: absent
        force: yes

    # This is required since the overlayfs snapshotter is not working with PXE filesystems
    - name: Enable 'native' snapshotter for MicroK8s
      lineinfile:
        path: "/var/snap/microk8s/current/args/containerd-template.toml"
        regexp: '^    snapshotter = "\$\{SNAPSHOTTER\}"'
        line: '    snapshotter = "native"'
        backup: yes

    - name: Start the MicroK8s service
      command: "/snap/bin/microk8s start"

    - name: Create an alias for kubectl 
      lineinfile:
        path: "/root/.bashrc" 
        line: 'alias kubectl="microk8s kubectl"'
        state: present
        create: yes

    - name: Verify MicroK8s is running
      command: '/snap/bin/microk8s status | grep "microk8s is running"'
