---
- name: Include snap role
  include_role:
    name: snap

- name: Check if MicroK8s is installed
  command: "snap list | grep microk8s"
  register: microk8s_snap_list
  check_mode: no
  ignore_errors: yes

- name: Print debug message if MicroK8s is not installed
  debug:
    msg: "No MicroK8s package found."
  when: microk8s_snap_list.failed

- name: Install MicroK8s
  when: microk8s_snap_list.failed
  block:
    - name: Restart snapd
      systemd:
        name: "snapd"
        state: restarted

    - name: Load the snapd daemon
      systemd:
        name: snapd
        state: started
        enabled: yes

    - name: Install linux-modules-extra-raspi on Ubuntu
      apt:
        name: "linux-modules-extra-raspi"
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Install MicroK8s snap
      snap:
        name: microk8s
        classic: yes
        state: present
    
    #- name: Stop MicroK8s
    #  command: "/snap/bin/microk8s stop"

    #- name: Remove the containerd directory
    #  file:
    #    path: /var/snap/microk8s/common/var/lib/containerd
    #    state: absent
    #    force: yes

    ## This is required since the overlayfs snapshotter is not working with PXE filesystems
    #- name: Enable 'native' snapshotter for MicroK8s
    #  lineinfile:
    #    path: "/var/snap/microk8s/current/args/containerd-template.toml"
    #    regexp: '^    snapshotter = "\$\{SNAPSHOTTER\}"'
    #    line: '    snapshotter = "native"'
    #    backup: yes

##  #  # https://github.com/canonical/microk8s/issues/1587#issuecomment-697207459
#   # - name: Disable LocalStorageCapacityIsolation
#   #   lineinfile:
#   #     path: "/var/snap/microk8s/current/args/kubelet"
#   #     backrefs: yes
#   #     regexp: "--feature-gates=DevicePlugins=true"
#   #     line: '--feature-gates=LocalStorageCapacityIsolation=false'

    #- name: Start the MicroK8s service
    #  command: "/snap/bin/microk8s start"

    - name: Create an alias for kubectl 
      lineinfile:
        path: "/root/.bashrc" 
        line: 'alias kubectl="microk8s kubectl"'
        state: present
        create: yes

    - name: Create an alias for helm
      lineinfile:
        path: "/root/.bashrc"
        line: 'alias helm="microk8s helm"'
        state: present
        create: yes
