---
- name: Include snap role
  include_role:
    name: snap

- name: Check if MicroK8s is installed
  command: "snap list | grep microk8s"
  register: microk8s_snap_list
  check_mode: no
  ignore_errors: yes

- name: Print debug message if MicroK8s is not installed
  debug:
    msg: "No MicroK8s package found."
  when: microk8s_snap_list.failed

- name: Install MicroK8s
  when: microk8s_snap_list.failed
  block:
    - name: Load the snapd daemon
      systemd:
        name: snapd
        state: started
        enabled: yes

    - name: Install linux-modules-extra-raspi on Ubuntu
      apt:
        name: "linux-modules-extra-raspi"
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Wait for snapd to start
      pause:
        minutes: 1

    - name: Install MicroK8s snap
      snap:
        name: microk8s
        classic: yes
        channel: '1.29/edge'
        state: present

    - name: Create an alias for kubectl 
      lineinfile:
        path: "/root/.bashrc" 
        line: 'alias kubectl="microk8s kubectl"'
        state: present
        create: yes

    - name: Create an alias for helm
      lineinfile:
        path: "/root/.bashrc"
        line: 'alias helm="microk8s helm"'
        state: present
        create: yes
