apiVersion: v2
name: elastic
description: A Helm chart for deploying the elastic (ECK) stack
type: application
version: 1.0.0

dependencies:
  - name: elastic/eck-operator
    repository: https://helm.elastic.co
    version: 0.7.0
