apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pvc.name }}
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.pvc.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.pvc.name }}
  nfs:
    path: /mnt/ssd/nfs/microk8s/{{ .Release.Namespace }}-{{ .Values.pvc.name }}
    server: 192.168.1.210
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvc.name }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size }}