apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend={{ .Values.frontend.image }}:latest
  name: myrecipes
  namespace: myrecipes
spec:
  destination:
    namespace: myrecipes
    server: https://kubernetes.default.svc
  project: default