apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    argocd.argoproj.io/managed-by: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: frontend=registry.myrecipes.at/myrecipes-frontend:latest
  name: myrecipes
  namespace: myrecipes
spec:
  destination:
    namespace: myrecipes
    server: https://kubernetes.default.svc
  project: default
