apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-backend
  labels:
    app: {{ .Values.ingress.service }}-backend
    chart: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 2 #should survive a node failure and allow for rolling deployments
  selector:
    matchLabels:
      app: {{ .Values.ingress.service }}-backend
      release: {{ .Release.Name }}
      component: backend
  template:
    metadata:
      labels:
        app: {{ .Values.ingress.service }}-backend
        release: {{ .Release.Name }}
        component: backend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ .Values.ingress.service }}-backend
              topologyKey: kubernetes.io/hostname
      containers:
        - name: backend
          image: {{ .Values.backend.image }}:{{ .Values.backend.version }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.ports.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.readinessProbe.path }}
              port: {{ .Values.backend.ports.targetPort }}
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.readinessProbe.failureThreshold }}
          env:
            - name: DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: mariadb-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingress.service }}-backend
spec:
  selector:
    app: {{ .Values.ingress.service }}-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.ports.port }}
      targetPort: {{ .Values.backend.ports.targetPort }}
