apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.service }}-ingress
  labels:
    name: nginx-ingress-microk8s
  annotations:
#    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/server-alias: "{{ .Values.ingress.alias }}"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.paths.frontend }}
            pathType: {{ .Values.ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .Values.ingress.service }}-frontend
                port:
                  number: {{ .Values.frontend.ports.port }}
          - path: {{ .Values.ingress.paths.backend }}
            pathType: {{ .Values.ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .Values.ingress.service }}-backend
                port:
                  number: {{ .Values.backend.ports.port }}
#  tls:
#    - hosts:
#        - {{ .Values.ingress.domain }}
#        - {{ .Values.ingress.alias }}
#      secretName: tls
