apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-harbor-postgresql-0
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: data-harbor-postgresql-0
  nfs:
    path: /mnt/ssd/nfs/microk8s/{{ .Release.Namespace }}-data-harbor-postgresql-0
    server: 192.168.1.210
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-harbor-postgresql-0
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-harbor-trivy-0
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: data-harbor-trivy-0
  nfs:
    path: /mnt/ssd/nfs/microk8s/{{ .Release.Namespace }}-data-harbor-trivy-0
    server: 192.168.1.210
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-harbor-trivy-0
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-jobservice
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: harbor-jobservice
  nfs:
    path: /mnt/ssd/nfs/microk8s/{{ .Release.Namespace }}-harbor-jobservice
    server: 192.168.1.210
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: harbor-jobservice
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-registry
spec:
  storageClassName: ""
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: harbor-registry
  nfs:
    path: /mnt/ssd/nfs/microk8s/{{ .Release.Namespace }}-harbor-registry
    server: 192.168.1.210
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: harbor-registry
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-harbor-redis-master-0
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: redis-data-harbor-redis-master-0
  nfs:
    path: /mnt/ssd/nfs/microk8s/{{ .Release.Namespace }}-redis-data-harbor-redis-master-0
    server: 192.168.1.210
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-harbor-redis-master-0
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
