ingress:
  domain: "myrecipes.at"
  hosts:
    grafana:
      - path: "/"
        serviceName: "kube-prom-stack-grafana"
        servicePort: "3000"
#    prometheus:
#      - path: "/"
#        serviceName: "kube-prom-stack-kube-prome-prometheus"
#        servicePort: "9090"
#    alertmanager:
#      - path: "/"
#        serviceName: "kube-prom-stack-kube-prome-alertmanager"
#        servicePort: "9093"

prometheus:
  server:
    persistentVolume:
      enabled: true
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi