apiVersion: v2
name: nfs-subdir-external-provisioner
description: A Helm chart for deploying the nfs-subdir-external-provisioner
type: application
version: 1.0.0

dependencies:
  - name: nfs-subdir-external-provisioner
    repository: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    version: 4.0.18