nfs-subdir-external-provisioner:
  nfs:
    server: 192.168.1.210
    path: /mnt/ssd/nfs/microk8s/
  storageClass:
    name: nfs
    defaultClass: false
    reclaimPolicy: Retain
    mountOptions:
      - hard
      - nfsvers=4
