pvc:
  name: kube-prometheus-stack-grafana
  size: 10Gi

kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      hosts:
        - grafana.myrecipes.at
    persistence:
      enabled: true
      storageClassName: nfs
