ingress:
  hosts:
    registry.myrecipes.at:
      - path: /
        serviceName: registry
        servicePort: 5000
    argocd.myrecipes.at:
      - path: /
        serviceName: argocd-server
        servicePort: 80
