pipeline {
    agent any
    
    stages {
	stage ('Restore all nodes') {
	    parallel {
                stage('node01') {
                    steps {
                        script {
                            def restorePipeline = build job: 'restore', parameters: [
                                string(name: 'NODE', value: 'node01'),
                            ]
                        }
                    }
                }
                stage('node02') {
                    steps {
                        script {
                            def restorePipeline = build job: 'restore', parameters: [
                                string(name: 'NODE', value: 'node02'),
                            ]
                        }
                    }
                }
                stage('node03') {
                    steps {
                        script {
                            def restorePipeline = build job: 'restore', parameters: [
                                string(name: 'NODE', value: 'node03'),
                            ]
                        }
                    }
                }
	    }
	}
    }
}
