apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-backend
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
      component: backend
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        component: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}:{{ .Values.backend.version }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.ports.port }}
          readinessProbe:
            httpGet:
              path: /recipes
              port: {{ .Values.backend.ports.targetPort }}
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.readinessProbe.failureThreshold }}
          env:
            - name: DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: mariadb-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingress.service }}-backend
spec:
  selector:
    app: {{ .Values.ingress.service }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.ports.port }}
      targetPort: {{ .Values.backend.ports.targetPort }}
