apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myrecipes-chart.fullname" . }}-frontend
  labels:
    app: {{ include "myrecipes-chart.name" . }}
    chart: {{ include "myrecipes-chart.chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "myrecipes-chart.name" . }}
      release: {{ .Release.Name }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ include "myrecipes-chart.name" . }}
        release: {{ .Release.Name }}
        component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}:{{ .Values.frontend.version }}
          ports:
            - containerPort: {{ index .Values.frontend.ports.targetPort }}
