apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-frontend
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd-image-updater.argoproj.io/image-list: {{ .Values.frontend.image }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}:{{ .Values.frontend.version }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.ports.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.readinessProbe.path }}
              port: {{ .Values.frontend.ports.targetPort }}
            initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.readinessProbe.failureThreshold }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingress.service }}-frontend
spec:
  selector:
    app: {{ .Values.ingress.service }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.ports.port }}
      targetPort: {{ .Values.frontend.ports.targetPort }}
