apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-frontend
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}:{{ .Values.frontend.version }}
          ports:
            - containerPort: {{ .Values.frontend.ports.port }}
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingress.service }}-frontend
spec:
  selector:
    app: {{ .Values.ingress.service }}-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.ports.port }}
      targetPort: {{ .Values.frontend.ports.targetPort }}
