apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingress.serviceName }}
spec:
  selector:
    app: {{ .Values.ingress.serviceName }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.ports.port }}
      targetPort: {{ .Values.frontend.ports.targetPort }}
