apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}-sa
roleRef:
  kind: ClusterRole
  name: {{ .Chart.Name }}-role
  apiGroup: rbac.authorization.k8s.io