apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-plant-and-seed-job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: mariadb-root-password
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              mysql -uroot -p$MYSQL_ROOT_PASSWORD -h mariadb < /mnt/schema/schema.sql &&
              mysql -uroot -p$MYSQL_ROOT_PASSWORD -h mariadb < /mnt/seed/seed.sql
          volumeMounts:
            - name: schema-volume
              mountPath: /mnt/schema
            - name: seed-volume
              mountPath: /mnt/seed
      volumes:
        - name: schema-volume
          configMap:
            name: schema-config
        - name: seed-volume
          configMap:
            name: seed-config
      restartPolicy: Never
