apiVersion: v1
kind: Service
metadata:
  name: ingress
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.loadBalancerIP }}
spec:
  selector:
    #name: ingress-nginx
    app: nginx
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443