apiVersion: v2
name: keycloak
description: A Helm chart for deploying keycloak
type: application
version: 1.0.0

dependencies:
  - name: keycloak
    repository: https://charts.bitnami.com/bitnami
    version: 16.1.7