apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-webpage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-webpage
      release: {{ .Release.Name }}
      component: sample-webpage
  template:
    metadata:
      labels:
        app: sample-webpage
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - sample-webpage-svc
              topologyKey: kubernetes.io/hostname
      volumes:
        - name: html-volume
          configMap:
            name: sample-webpage-configmap