apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-webpage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-webpage
  template:
    metadata:
      labels:
        app: sample-webpage
    spec:
      containers:
        - name: flask
          image: sbrakl/flask:latest
          ports:
            - containerPort: 5000