apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-webpage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-webpage
  template:
    metadata:
      labels:
        app: sample-webpage
    spec:
      containers:
        - name: sample-webpage
          image: registry.myrecipes.at/python-flask-docker:latest
          ports:
            - containerPort: 8080