{{- if .Values.enable }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ .Values.name }}"
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: nfs.csi.k8s.io
parameters:
  server: "{{ .Values.server }}"
  share: "{{ .Values.path }}"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4
{{- end }}