persistence:
  enabled: "true"
  size: "20Gi"
  accessMode: "ReadWriteOnce"
  deleteEnabled: "true"
  storageClass: "nfs-csi"
  existingClaim: "registry-claim"

ingress:
  host: "registry"
  domain: "myrecipes.at"
  path: "/"
  serviceName: "registry-docker-registry"
  servicePort: "5000"
