pvc:
  #storageSize: "40Gi"
  storageSize: "10Gi"
  #storageClassName: "nfs-csi"
  storageClassName: "microk8s-hostpath"

ingress:
  host: "registry"
  domain: "myrecipes.at"
  path: "/"
  serviceName: "registry-docker-registry"
  servicePort: "5000"
