apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.loadBalancerIP }}
spec:
  selector:
    app: ingress-nginx
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443