apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.214
spec:
  ports:
    - port: 80
      targetPort: http
    - port: 443
      targetPort: https
  selector:
    app: nginx
  type: LoadBalancer