apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels:
    app: nginx-ingress-microk8s
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  rules:
    {{- range $host, $paths := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          {{- range $pathIndex, $path := $paths }}
          - path: {{ $path.path }}
            pathType: {{ $path.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $path.serviceName }}
                port:
                  number: {{ $path.servicePort }}
          {{- end }}
    {{- end }}