apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: denis.radovanovic@web.de
    privateKeySecretRef:
      name: letsencrypt-microk8s
    solvers:
      - http01:
          ingress:
            class: public
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: denis.radovanovic@web.de
    privateKeySecretRef:
      name: letsencrypt-microk8s
    solvers:
      - http01:
          ingress:
            class: public
