pipeline {
    agent any

    stages {
        stage('Clone Repositories') {
            steps {
                dir('python-flask-docker') {
                    checkout([$class           : 'GitSCM',
                              branches         : [[name: '*/master']],
                              userRemoteConfigs: [[url: 'https://github.com/lvthillo/python-flask-docker.git']],
                              clean            : true
                    ])
                }
                dir('MyRecipes') {
                    checkout([$class           : 'GitSCM',
                              branches         : [[name: '*/main']],
                              userRemoteConfigs: [[url: 'https://github.com/SycSin/MyRecipes.git']],
                              clean            : true
                    ])
                }
            }
        }
        stage('Build Sample-WebApp') {
            steps {
                dir('python-flask-docker') {
                    script {
                        webAppImage = docker.build("registry.myrecipes.at/python-flask-docker")
                    }
                }
            }
        }
        stage('Build Backend') {
            steps {
                dir('MyRecipes/backend') {
                    script {
                        backendImage = docker.build("harbor.myrecipes.at/myrecipes-backend:${env.BUILD_NUMBER}")
                    }
                }
            }
        }
        stage('Build Frontend') {
            steps {
                dir('MyRecipes/frontend') {
                    script {
                        frontendImage = docker.build("registry.myrecipes.at/myrecipes-frontend:${env.BUILD_NUMBER}")
                    }
                }
            }
        }
        stage('Push Sample-WebApp') {
            steps {
                script {
                    docker.withRegistry("https://registry.myrecipes.at") {
                        webAppImage.push()
                    }
                }
            }
        }
        stage('Push Backend') {
            steps {
                script {
                    docker.withRegistry("https://harbor.myrecipes.at", "harbor") {
                        backendImage.push()
                    }
                }
            }
        }
        stage('Push Frontend') {
            steps {
                script {
                    docker.withRegistry("https://registry.myrecipes.at") {
                        frontendImage.push()
                    }
                }
            }
        }
        stage('Tag MyRecipes Images') {
            steps {
                script {
                    def backendImage = docker.image("harbor.myrecipes.at/myrecipes-backend:${env.BUILD_NUMBER}")
                    def frontendImage = docker.image("registry.myrecipes.at/myrecipes-frontend:${env.BUILD_NUMBER}")

                    backendImage.tag("latest")
                    frontendImage.tag("latest")

                    backendImage = docker.image("harbor.myrecipes.at/myrecipes-backend:latest")
                    frontendImage = docker.image("registry.myrecipes.at/myrecipes-frontend:latest")
                    backendImage.push()
                    frontendImage.push()
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}