pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                checkout([$class: 'GitSCM',
                          branches: [[name: '*/main']],
                          userRemoteConfigs: [[url: 'https://github.com/SycSin/MyRecipes.git']]
                ])
            }
        }
        stage('Build Backend') {
            steps {
                dir('backend') {
                    script {
                        backendImage = docker.build("registry.myrecipes.at/myrecipes-backend:${env.BUILD_NUMBER}")
                    }
                }
            }
        }
        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    script {
                        frontendImage = docker.build("registry.myrecipes.at/myrecipes-frontend:${env.BUILD_NUMBER}")
                    }
                }
            }
        }
        stage('Push Backend') {
            steps {
                script {
                    docker.withRegistry("https://registry.myrecipes.at") {
                        backendImage.push()
                    }
                }
            }
        }
        stage('Push Frontend') {
            steps {
                script {
                    docker.withRegistry("https://registry.myrecipes.at") {
                        frontendImage.push()
                    }
                }
            }
        }
        stage('Tag Images') {
            steps {
                script {
                    def backendImage = docker.image("registry.myrecipes.at/myrecipes-backend:${env.BUILD_NUMBER}")
                    def frontendImage = docker.image("registry.myrecipes.at/myrecipes-frontend:${env.BUILD_NUMBER}")

                    backendImage.tag("latest")
                    frontendImage.tag("latest")

                    backendImage = docker.image("registry.myrecipes.at/myrecipes-backend:latest")
                    frontendImage = docker.image("registry.myrecipes.at/myrecipes-frontend:latest")
                    backendImage.push()
                    frontendImage.push()
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}