loadBalancerIP: 192.168.1.214
ingress-nginx:
  controller:
    replicaCount: 2
    config:
      use-forwarded-headers: "true"
      forwarded-for-header: "X-Forwarded-For"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - nginx-ingress
            topologyKey: "kubernetes.io/hostname"
