pgadmin4:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Script-Name /pgadmin-stage;
    hosts:
      - host: pgadmin.myrecipes.at
        paths:
          - /pgadmin-stage
  persistentVolume:
    storageClass: nfs-csi