pgadmin4:
  env:
    email: "admin@myrecipes.at"
    password: pgadmin-test123
  serverDefinitions:
    enabled: true
    servers:
      Keycloak:
        Name: "Keycloak DB"
        Group: "Servers"
        Port: 5432
        Username: "postgres"
        Host: "keycloak-postgresql.keycloak.svc.cluster.local"
        SSLMode: "prefer"
        MaintenanceDB: "postgres"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx" #
      # When setting `ingress.hosts.paths`, pgAdmin needs additional header to be passed.
      # Ref: https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html#http-via-nginx
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Script-Name /pgadmin4;
      # If TLS is terminated elsewhere (on external load balancer), you may want
      # to redirect to `https://` URL scheme along with rewriting URL path if
      # `ingress.hosts.paths` is set. This is specific for image version >= 4.22.
      # Ref: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#proxy-redirect
      nginx.ingress.kubernetes.io/proxy-redirect-from: "~^http://([^/]+)/(pgadmin4/)?(.*)$"
      nginx.ingress.kubernetes.io/proxy-redirect-to: "https://$1/pgadmin4/$3"
    hosts:
      - host: pgadmin.myrecipes.at
        paths:
          - path: /
            pathType: ImplementationSpecific
  persistentVolume:
    storageClass: nfs-csi