argo-cd:
  global:
    #domain: argocd.myrecipes.at
    domain: localhost
  configs:
    params:
      server.insecure: true
    cm:
      timeout.reconciliation: 15s
      oidc.config: |
        name: Keycloak
        issuer: http://localhost:8085/realms/master
        clientID: argocd
        clientSecret: $oidc.keycloak.clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]
      #oidc.config: |
      #    name: Keycloak
      #    issuer: http://keycloak.myrecipes.at/realms/master
      #    clientID: argocd
      #    clientSecret: $oidc.keycloak.clientSecret
      #    requestedScopes:
      #      - openid
      #      - profile
      #      - email
      #      - groups
  certificate:
      enabled: true
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTP
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      tls: true
  #  autoscaling:
  #    enabled: true
  #    minReplicas: 2
  #repoServer:
  #  autoscaling:
  #    enabled: true
  #    minReplicas: 2
  #applicationSet:
  #  replicas: 2
  #redis-ha:
  #  enabled: true
  #controller:
  #  replicas: 1
