argo-cd:
  global:
    domain: argocd.myrecipes.at
  crds:
    install: false #installed via cluster-setup pipeline
  configs:
    params:
      server.insecure: true
    cm:
      timeout.reconciliation: 5s
  redis-ha:
    enabled: true
  controller:
    replicas: 1
  certificate:
      enabled: true
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/cors-expose-headers: "*, X-CustomResponseHeader"
      tls: true
    autoscaling:
      enabled: true
      minReplicas: 2
  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 2
  applicationSet:
    replicas: 2
