ingress:
  host: "argocd"
  domain: "myrecipes.at"
  path: "/"
  #serviceName: "argo-cd-argocd-server"
  serviceName: "argocd-server"
  servicePort: "443"
argo-cd:
  redis-ha:
    enabled: true
  controller:
    replicas: 1
  server:
    autoscaling:
      enabled: true
      minReplicas: 2
  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 2
  applicationSet:
    replicas: 2
