argo-cd:
  global:
    domain: argocd.myrecipes.at
  configs:
    params:
      server.insecure: true
    cm:
      timeout.reconciliation: 5s
  redis-ha:
    enabled: true
  controller:
    replicas: 1
  certificate:
      enabled: true
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      tls: true
    autoscaling:
      enabled: true
      minReplicas: 2
  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 2
  applicationSet:
    replicas: 2
