argo-cd:
  global:
    domain: argocd.myrecipes.at
  configs:
    params:
      server.insecure: true
  redis-ha:
    enabled: true
  controller:
    replicas: 1
  certificate:
      enabled: true
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      tls: true
    autoscaling:
      enabled: true
      minReplicas: 2
  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 2
  applicationSet:
    replicas: 2
