argo-cd:
  global:
    domain: argocd.myrecipes.at
  configs:
    params:
      server.insecure: true
  redis-ha:
    enabled: true
  controller:
    replicas: 1
  server:
    autoscaling:
      enabled: true
      minReplicas: 2
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      extraTls:
        - hosts:
            - argocd.myrecipes.at
  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 2
  applicationSet:
    replicas: 2
