pipeline {
    agent any

    parameters {
        choice(name: 'WORKER', choices: ['worker01', 'worker02', 'worker03'], description: 'Select a worker')
    }

    environment {
        SSH_HOST = '192.168.1.210'
        SSH_COMMAND = "rsync -a --delete /mnt/ssd/nfs/worker-base-template/ /mnt/ssd/nfs/${params.WORKER}"
    }

    stages {
        stage('SSH and Execute Rsync') {
            steps {
                script {
                    // Get the SSH private key from Jenkins credentials
                    def sshPrivateKey = credentials('jenkins-private-key-base64')
                    if (sshPrivateKey == null) {
                        error("Failed to retrieve SSH private key from Jenkins credentials")
                    }

                    // Start the SSH agent and run the rsync command
                    sshagent(credentials: [sshPrivateKey]) {
                        sh "ssh -o StrictHostKeyChecking=no root@${SSH_HOST} \"$SSH_COMMAND\""
                    }
                }
            }
        }
    }
}
