pipeline {
    agent any

    parameters {
        choice(
            choices: 'worker01\nworker02\nworker03',
            description: 'Select the worker',
            name: 'WORKER'
        )
    }

    stages {
        stage('Run rsync on Worker') {
            steps {
                script {
                    def worker = params.WORKER
                    echo "Selected worker: $worker"

                    // Define the target host and SSH credentials ID
                    def user = "root"
                    def targetHost = "192.168.1.210"
                    def sshCredentials = "jenkins-private-key-base64"

                    // Retrieve the SSH private key from the Jenkins credentials
                    def privateKey = credentials("${sshCredentials}")

                    // Execute rsync command using withEnv block to pass the private key as an environment variable
                    withEnv(["SSH_PRIVATE_KEY=${privateKey}"]) {
                        sh "echo '\${SSH_PRIVATE_KEY}' > ssh_key"
                        sh "chmod 400 ssh_key"
                        //sh "ssh -o StrictHostKeyChecking=no -i ssh_key \"rsync -a -e /mnt/ssd/nfs/worker-base-template/ root@${targetHost}:/mnt/ssd/nfs/${worker}\""
                        sh 'ssh -o StrictHostKeyChecking=no -i ssh_key "ip a"'
                    }
                }
            }
        }
    }
}
