pipeline {
    agent any
    
    parameters {
        choice(
            choices: 'worker01\nworker02\nworker03',
            description: 'Select the worker',
            name: 'WORKER'
        )
    }
    
    stages {
        stage('Run rsync on Worker') {
            steps {
                script {
                    def worker = params.WORKER
                    echo "Selected worker: $worker"
                   
                    // Define the target host and SSH credentials ID
                    def targetHost = "192.168.1.210"
                    def sshCredentials = "jenkins-private-key"
                    
                    // Execute rsync command using ssh command with targetHost and sshCredentials
                    sh "ssh -o StrictHostKeyChecking=no -l user -i ${sshCredentials} ${targetHost} rsync -a --delete /mnt/ssd/nfs/worker-base-template/ /mnt/ssd/nfs/${worker}"
                }
            }
        }
    }
}
