apiVersion: v2
name: mariadb
namespace: myrecipes
description: A Helm chart for deploying a MariaDB Database Cluster
type: application
version: 1.0.0

dependencies:
  - name: mariadb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 13.1.1
