{{ if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-prom-stack-grafana
  namespace: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-prom-stack
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kube-prom-stack
        app.kubernetes.io/name: grafana
    spec:
      containers:
        - name: grafana
          volumeMounts:
            - mountPath: "/var/lib/grafana"
              name: grafana
      volumes:
        - name: grafana
          persistentVolumeClaim:
            claimName: grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prom-stack-grafana
  namespace: observability
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [database]
    wal = true
    cache_mode = shared
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''
{{ end -}}
