{{ if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-prom-stack-grafana
  namespace: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-prom-stack
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kube-prom-stack
        app.kubernetes.io/name: grafana
    spec:
      containers:
        - name: grafana
          volumeMounts:
            - mountPath: "/var/lib/grafana"
              name: grafana
      volumes:
        - name: grafana
          persistentVolumeClaim:
            claimName: grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prom-stack-grafana
  namespace: observability
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.myrecipes.at
    [database]
    wal = true
    cache_mode = shared
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = grafana.myrecipes.at
    root_url = https://grafana.myrecipes.at/
    [auth.generic_oauth]
    enabled = true
    name = Keycloak
    allow_sign_up = true
    client_id = grafana
    client_secret = NGxAzFLqjMCsy9AgDB0j0p5aKuEvYfWK
    scopes = openid email profile offline_access roles
    email_attribute_path = email
    login_attribute_path = username
    name_attribute_path = full_name
    auth_url = https://keycloak.myrecipes.at/realms/master/protocol/openid-connect/auth
    token_url = https://keycloak.myrecipes.at/realms/master/protocol/openid-connect/token
    api_url = https://keycloak.myrecipes.at/realms/master/protocol/openid-connect/userinfo
    role_attribute_path = contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
{{ end -}}
