{{ if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
  {{- range $host, $paths := .Values.ingress.hosts }}
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: {{ $host }}-ingress
      labels:
        name: nginx-ingress-microk8s
      annotations:
        nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
        nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
      {{- end }}
    spec:
      rules:
        {{- range $host, $paths := .Values.ingress.hosts }}
        - host: {{ $host }}.{{ $.Values.ingress.domain }}
          http:
            paths:
              {{- range $pathIndex, $path := $paths }}
              - path: {{ $path.path }}
                pathType: {{ $path.pathType | default "Prefix" }}
                backend:
                  service:
                    name: {{ $path.serviceName }}
                    port:
                      number: {{ $path.servicePort }}
              {{- end }}
    {{- end }}
{{- end }}