{{ if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- range $host, $paths := .Values.ingress.hosts }}
  name: {{ $host }}-ingress
  labels:
    name: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    cert-manager.io/cluster-issuer: letsencrypt
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
    {{- range $host, $paths := .Values.ingress.hosts }}
    - host: {{ $host }}.{{ $.Values.ingress.domain }}
      http:
        paths:
          {{- range $pathIndex, $path := $paths }}
          - path: {{ $path.path }}
            pathType: {{ $path.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $path.serviceName }}
                port:
                  number: {{ $path.servicePort }}
  tls:
    - hosts:
        - grafana.myrecipes.at
      secretName: letsencrypt
          {{- end }}
    {{- end }}
{{- end }}
