{{ if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: observability
spec:
  replicas: 1 #set to 0 due to resource constraints on the rpi4
  selector:
    matchLabels:
      app: loki
      release: loki
  template:
    metadata:
      labels:
        app: loki
        release: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.6.1
          args:
            - '-config.file=/etc/loki/loki.yaml'
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: memberlist-port
              containerPort: 7946
              protocol: TCP
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
              scheme: HTTP
            initialDelaySeconds: 45
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
              scheme: HTTP
            initialDelaySeconds: 45
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: tmp
          emptyDir: {}
        - name: config
          secret:
            secretName : loki
            defaultMode : 420
        - name : storage
          emptyDir : {}
  serviceName: loki-headless
{{ end -}}
