apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "myrecipes"
data:
  mariadb-root-password: {{ .Values.initialPassword | b64enc | quote }}
type: Opaque
