harbor:
  exposureType: ingress
  ingress:
    core:
      ingressClassName: nginx
      hostname: registry.myrecipes.at
      tls: true
      selfSigned: true
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
  externalURL: https://registry.myrecipes.at
