harbor:
  exposureType: ingress
  ingress:
    core:
      ingressClassName: nginx
      hostname: harbor.myrecipes.at
      tls: true
      selfSigned: true
  externalURL: https://harbor.myrecipes.at
