harbor:
  exposureType: ingress
  ingress:
    core:
      ingressClassName: nginx
      hostname: registry.myrecipes.at
      tls: true
      selfSigned: true
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
  externalURL: https://registry.myrecipes.at
  core:
    extraEnvVars:
      - name: configOverwriteJson
        value: |
          {
            "auth_mode": "oidc_auth",
            "oidc_name": "Keycloak",
            "oidc_endpoint": "https://keycloak.myrecipes.at/realms/master",
            "oidc_groups_claim": "groups",
            "oidc_admin_group": "HarborAdmins",
            "oidc_client_id": "harbor",
            "oidc_client_secret": "BQ3xIZsv3FWXDEOX5u7hDfifmQwC7CFS",
            "oidc_scope": "openid,email,profile,offline_access",
            "oidc_verify_cert": "false",
            "oidc_auto_onboard": "true",
            "oidc_user_claim": "preferred_username"
          }
