frontend:
  image: "registry.myrecipes.at/myrecipes/myrecipes-frontend"
  version: "latest"
  ports:
    name: http
    port: 8080
    targetPort: 8080
  readinessProbe:
    path: "/"
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 10

backend:
  image: "registry.myrecipes.at/myrecipes/myrecipes-backend"
  version: "latest"
  ports:
    name: http
    port: 3000
    targetPort: 3000
  readinessProbe:
    path: "/recipes"
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 10

ingress:
  domain: "myrecipes.at"
  alias: "www.myrecipes.at"
  service: "myrecipes"
  paths:
    frontend: "/(.*)"
    backend: "/api/(.*)"
