apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pet-configuration
  namespace: openshift-gitops
spec:
  goTemplate: true
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: rolloutOrder
              operator: In
              values:
                - "0"
        - matchExpressions:
            - key: rolloutOrder
              operator: In
              values:
                - "1"
        - matchExpressions:
            - key: rolloutOrder
              operator: NotIn
              values:
                - "0"
                - "1"
  generators:
    #helm chart apps
    - git:
        repoURL: https://git.lottery.co.at/it-dev/pet/cluster-config.git
        revision: ${ENVIRONMENT}
        files:
          - path: "helm/*/config.yml"
          - path: "helm/*/config-${ENVIRONMENT}.yml"
        template:
          metadata: {}
          spec:
            project: "default"
            destination: {}
            source:
              repoURL: https://git.lottery.co.at/it-dev/pet/cluster-config.git
              helm:
                valueFiles:
                  - values-${ENVIRONMENT}.yml
                parameters:
                  - name: "environment"
                    value: ${ENVIRONMENT}
                  - name: "clusterName"
                    value: ${CLUSTER_NAME}
                  - name: "clusterActive"
                    value: "${CLUSTER_ACTIVE}"
                  - name: "aws.accountId"
                    value: "${AWS_ACCOUNT}"
  template:
    metadata:
      name: '{{.path.basename}}'
      labels:
        rolloutOrder: '{{default "2" .rolloutOrder}}'
      annotations:
        notifications.argoproj.io/subscribe.smtpRelay: '{{ default "" .notification.email }}'
    spec:
      project: "default"
      source:
        repoURL: https://git.lottery.co.at/it-dev/pet/cluster-config.git
        targetRevision: ${ENVIRONMENT}
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - 'CreateNamespace={{.syncOptions.CreateNamespace}}'
          - 'ServerSideApply={{.syncOptions.ServerSideApply}}'
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: openshift-gitops