apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pgadmin-pgadmin4-7df986d44
  namespace: pgadmin
  labels:
    app.kubernetes.io/instance: pgadmin
    app.kubernetes.io/name: pgadmin4
    pod-template-hash: 7df986d44
  annotations:
    deployment.kubernetes.io/desired-replicas: '1'
    deployment.kubernetes.io/max-replicas: '2'
    deployment.kubernetes.io/revision: '1'
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: pgadmin-pgadmin4
      uid: fa2c16f9-588a-4a61-ae65-70c6212d4e6d
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: kubelite
      operation: Update
      apiVersion: apps/v1
      time: '2024-03-01T11:53:03Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:fullyLabeledReplicas: {}
          f:observedGeneration: {}
          f:replicas: {}
      subresource: status
  selfLink: /apis/apps/v1/namespaces/pgadmin/replicasets/pgadmin-pgadmin4-7df986d44
status:
  replicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: pgadmin
      app.kubernetes.io/name: pgadmin4
      pod-template-hash: 7df986d44
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: pgadmin
        app.kubernetes.io/name: pgadmin4
        pod-template-hash: 7df986d44
    spec:
      volumes:
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: pgadmin-pgadmin4
      initContainers:
        - name: pgadmin-data-permission-fix
          image: busybox
          command: ["/bin/chown", "-R", "5050:5050", "/var/lib/pgadmin"]
          volumeMounts:
            - name: pgadminstorage
              mountPath: /var/lib/pgadmin
      containers:
        - name: pgadmin4
          image: docker.io/dpage/pgadmin4:8.3
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
              value: 'False'
            - name: PGADMIN_DEFAULT_EMAIL
              value: chart@domain.com
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-pgadmin4
                  key: password
          resources: {}
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
          livenessProbe:
            httpGet:
              path: /misc/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 15
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /misc/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 15
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 5050
        runAsGroup: 5050
        fsGroup: 5050
      schedulerName: default-scheduler
