pvc:
  name: docker-docker-registry
  size: 20Gi

ingress:
  host: "registry"
  domain: "myrecipes.at"
  path: "/"
  serviceName: "registry-docker-registry"
  servicePort: "5000"

docker-registry:
  persistence:
    enabled: true
    size: 20Gi
    accessMode: "ReadWriteOnce"
    deleteEnabled: true
