---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-kube-image-keeper-registry-0
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: data-kube-image-keeper-registry-0