frontend:
  image: "registry.myrecipes.at/myrecipes-frontend"
  version: "58"
  ports:
    name: http
    port: 8080
    targetPort: 8080
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 10

backend:
  image: "registry.myrecipes.at/myrecipes-backend"
  version: "58"
  ports:
    name: http
    port: 3000
    targetPort: 3000
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 10

ingress:
  domain: "myrecipes.at"
  alias: "www.myrecipes.at"
  service: "myrecipes"
  paths:
    frontend: "/(.*)"
    backend: "/api/(.*)"
